/* Shared mutable application state. One store, owned here; every view
   reads and writes through `S` so modules stay free of import cycles. */

export const SETTINGS_PANELS = ['appearance', 'occupancy', 'advanced'];

export const CARD_FIELD_KEYS = {
  show_status_text: true,
  show_access_badge: true,
  show_protocol_badge: true,
};

export const CORE_THEMES = ['system', 'dark', 'light'];

export const S = {
  currentData: null,
  hostCatalog: { local: { id: 'local', name: '', local: true }, peers: [], readonly: false },
  hostMaps: {},
  focusHostId: 'local',
  selectedHostId: 'local',
  hostAborts: {},
  hostEtags: {},
  hostRetrying: {},
  peersDraft: [],
  statusFilter: 'all',
  kindFilters: new Set(),
  sortMode: 'port-asc',
  searchTerm: '',
  searchPortNum: null,
  selectedPort: null,
  rangeStart: 1,
  rangeEnd: 9999,
  rangeFromView: false,
  showHidden: false,
  settings: {
    locale: 'auto',
    theme: 'system',
    grid_density: 'comfortable',
    show_status_text: false,
    show_access_badge: true,
    show_protocol_badge: true,
    copy_on_click: true,
    auto_refresh: true,
    refresh_ms: 5000,
    port_range_start: 1,
    port_range_end: 9999,
    guess_urls: true,
    url_host: '',
    url_scheme: 'auto',
  },
  settingsDoc: null,
  settingsDirty: false,
  settingsPanel: 'appearance',
  refreshTimer: null,
  meta: { hidden_unlock_required: false, hidden_ports_withheld: false, version: '', settings_readonly: false },
  hiddenUnlock: sessionStorage.getItem('port-light-hidden-unlock') || '',
  route: { name: 'grid' },
  pendingAfterUnlock: null,
  pendingUnlockFocus: 'eye',
  focusBack: null,
  pendingGridFocus: null,
  occupancyKey: '',
  portsEtag: '',
  portsEtagUrl: '',
  portDetailGen: 0,
  detailShownPort: null,
  knownCache: {},
  knownInflight: {},
  knownRenderFrame: 0,
  lockedHitCache: {},
  lockedHitInflight: {},
  lastHiddenLocked: null,
  portsAbort: null,
};
